import Navbar from "@/components/Navbar";
import "./globals.css";
import { Figtree, Inter } from "next/font/google";

const figtree = Figtree({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
