import Navbar from "@/components/Navbar";
import "./globals.css";
import { Figtree, Inter, Sacramento } from "next/font/google";
import ToasterContext from "@/context/ToasterContext";
import cn from "@/lib/utils";
import Footer from "@/components/Footer";

const figtree = Figtree({ subsets: ["latin"] });
const sacramento = Sacramento({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cursive",
});
export const metadata = {
  title: "Jaipur Event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(figtree.className, sacramento.variable)}>
        <ToasterContext />
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
